version: "3.7"
services:

  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb/guitar-geek
    depends_on:
      - mongodb


  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
