version: "3"
services:

  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    volumes:
      - guitar-geek-data:/db/data/db




# services:
#   db:
#     image: mongo:3.1
#     environment:
#       - MONGO_DATA_DIR=/data/db
#     expose:
#       - "2707"
#     ports:
#       - "2707:2707"
#     volumes:
#       - guitar-geek-data:/db/data/db
#     restart: always
#     command: mongod
#
#   web:
#     image: alishalabi/guitar-geek-node:latest
#     env_file: .env
#     expose:
#       - "3000"
#     ports:
#       - "3000:3000"
#     restart: always
#     depends_on:
#       - db

volumes:
  guitar-geek-data:
